/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaodeeficienciadealunos.forms;

import br.com.gestaodeeficienciadealunos.Complexidade;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormComplexidade extends javax.swing.JFrame {

    DefaultTableModel modelo_tabela = new DefaultTableModel();
    FormMain main_screen;
    Complexidade cp;
    
    public FormComplexidade(FormMain main_screen) {
        this.main_screen = main_screen;
        initComponents();
        
        tabela_complexidade.setModel(modelo_tabela);
        
        modelo_tabela.addColumn("Código");
        modelo_tabela.addColumn("Complexidade");
        
        cp = new Complexidade(modelo_tabela);
        try
        {
            cp.iniciar();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_codigo = new javax.swing.JTextField();
        campo_complexidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_complexidade = new javax.swing.JTable();
        btn_incluir = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_resetar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Complexidade");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Complexidade:");

        campo_codigo.setEditable(false);

        tabela_complexidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Complexidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela_complexidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_complexidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_complexidade);

        btn_incluir.setText("Incluir");
        btn_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_incluirActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_resetar.setText("Resetar");
        btn_resetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_complexidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_consultar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_resetar)
                                .addGap(137, 137, 137)
                                .addComponent(btn_incluir)
                                .addGap(18, 18, 18)
                                .addComponent(btn_atualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_excluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_complexidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_incluir)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_consultar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_resetar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_incluirActionPerformed
        cp.setComplexidade(campo_complexidade.getText());
        
        try
        {
            cp.salvar(cp);
            modelo_tabela.addRow((Object[]) cp.getRowObject());
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_incluirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        main_screen.setEnabled(true);
        main_screen.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        if(campo_codigo.getText().equals(""))
        {
            cp.setCodigo(0);
        }
        else
        {
            cp.setCodigo(Integer.parseInt(campo_codigo.getText()));
        }
        cp.setComplexidade(campo_complexidade.getText());
        
        try
        {
            cp.consultar(cp);
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_resetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetarActionPerformed
        try
        {
            cp.resetTable();
            campo_codigo.setText("");
            campo_complexidade.setText("");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_resetarActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        cp.setCodigo(Integer.parseInt(campo_codigo.getText()));
        cp.setComplexidade(campo_complexidade.getText());
        
        try
        {
            cp.editar(cp);
            cp.resetTable();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void tabela_complexidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_complexidadeMouseClicked
        String codigo = modelo_tabela.getValueAt(tabela_complexidade.getSelectedRow(), 0).toString();
        String complexidade = modelo_tabela.getValueAt(tabela_complexidade.getSelectedRow(), 1).toString();
        
        campo_codigo.setText(codigo);
        campo_complexidade.setText(complexidade);
    }//GEN-LAST:event_tabela_complexidadeMouseClicked

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int id = (int) modelo_tabela.getValueAt(tabela_complexidade.getSelectedRow(), 0);

        try{
            if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este item?") == 0)
            {
                cp.deletar(id);
                modelo_tabela.removeRow(tabela_complexidade.getSelectedRow());
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_incluir;
    private javax.swing.JButton btn_resetar;
    private javax.swing.JTextField campo_codigo;
    private javax.swing.JTextField campo_complexidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_complexidade;
    // End of variables declaration//GEN-END:variables
}
