/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaodeeficienciadealunos.forms;

import br.com.gestaodeeficienciadealunos.Solucao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormSolucao extends javax.swing.JFrame{

    DefaultTableModel modelo_tabela = new DefaultTableModel();
    FormMain main_screen;
    Solucao ap;
        
    public FormSolucao(FormMain main_screen) {
        this.main_screen = main_screen;       
        initComponents();
        
        tabela_area_pesquisa.setModel(modelo_tabela);
        
        modelo_tabela.addColumn("Código Solução");
        modelo_tabela.addColumn("Código Algoritmo");
        modelo_tabela.addColumn("Descrição da solução");
        modelo_tabela.addColumn("Descrição do computador");
        modelo_tabela.addColumn("Nome do arquivo");
        
        ap = new Solucao(modelo_tabela);
        try
        {
            ap.iniciar();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_codigo = new javax.swing.JTextField();
        campo_codigo_algoritmo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_area_pesquisa = new javax.swing.JTable();
        btn_incluir = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        campo_descricao_solucao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_resetar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campo_descricao_computador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campo_arquivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Solução");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Código solução:");

        jLabel2.setText("Código algoritmo");

        campo_codigo.setEditable(false);

        tabela_area_pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_area_pesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_area_pesquisa);

        btn_incluir.setText("Incluir");
        btn_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_incluirActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição computador:");

        btn_resetar.setText("Resetar");
        btn_resetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetarActionPerformed(evt);
            }
        });

        jLabel4.setText("Descrição solução:");

        jLabel5.setText("Arquivo solução:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_arquivo)
                            .addComponent(campo_descricao_solucao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_consultar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_resetar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_incluir)
                                .addGap(18, 18, 18)
                                .addComponent(btn_atualizar)
                                .addGap(150, 150, 150)
                                .addComponent(btn_excluir))
                            .addComponent(campo_descricao_computador)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campo_codigo_algoritmo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_codigo_algoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_descricao_solucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campo_descricao_computador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campo_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_incluir)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_consultar)
                    .addComponent(btn_resetar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_incluirActionPerformed

        ap.setCodigoAlgoritmo(Integer.parseInt(campo_codigo_algoritmo.getText()));
        ap.setDescricaoSolucao(campo_descricao_solucao.getText());
        
        try
        {
            ap.salvar(ap);
            modelo_tabela.addRow((Object[]) ap.getRowObject());
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_incluirActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        
        int id = (int) modelo_tabela.getValueAt(tabela_area_pesquisa.getSelectedRow(), 0);

        try{
            if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este item?") == 0)
            {
                ap.deletar(id);
                modelo_tabela.removeRow(tabela_area_pesquisa.getSelectedRow());
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void tabela_area_pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_area_pesquisaMouseClicked
        String codigoSol = modelo_tabela.getValueAt(tabela_area_pesquisa.getSelectedRow(), 0).toString();
        String codigoAlg = modelo_tabela.getValueAt(tabela_area_pesquisa.getSelectedRow(), 1).toString();
        String descSol = modelo_tabela.getValueAt(tabela_area_pesquisa.getSelectedRow(), 2).toString();
        String descComp = modelo_tabela.getValueAt(tabela_area_pesquisa.getSelectedRow(), 3).toString();
        String arquivo = modelo_tabela.getValueAt(tabela_area_pesquisa.getSelectedRow(), 4).toString();
        
        campo_codigo.setText(codigoSol);
        campo_codigo_algoritmo.setText(codigoAlg);
        campo_descricao_solucao.setText(descSol);
        campo_descricao_computador.setText(descComp);
        campo_arquivo.setText(arquivo);
    }//GEN-LAST:event_tabela_area_pesquisaMouseClicked

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed

        ap.setCodigoSolucao(Integer.parseInt(campo_codigo.getText()));
        ap.setCodigoAlgoritmo(Integer.parseInt(campo_codigo_algoritmo.getText()));
        ap.setDescricaoSolucao(campo_descricao_solucao.getText());
        ap.setDescricaoComputador(campo_descricao_computador.getText());
        ap.setArquivo(campo_arquivo.getText());
        
        try
        {
            ap.editar(ap);
            ap.resetTable();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        main_screen.setEnabled(true);
        main_screen.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        
        if(campo_codigo.getText().equals(""))
        {
            ap.setCodigoSolucao(0);
        }
        else
        {
            ap.setCodigoSolucao(Integer.parseInt(campo_codigo.getText()));
        }
        ap.setDescricaoSolucao(campo_descricao_solucao.getText());
        ap.setDescricaoComputador(campo_descricao_computador.getText());
        ap.setArquivo(campo_arquivo.getText());
        
        try
        {
            ap.consultar(ap);
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_resetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetarActionPerformed
        try
        {
            ap.resetTable();
            campo_codigo.setText("");
            campo_codigo_algoritmo.setText("");
            campo_descricao_solucao.setText("");
            campo_descricao_computador.setText("");
            campo_arquivo.setText("");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_resetarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_incluir;
    private javax.swing.JButton btn_resetar;
    private javax.swing.JTextField campo_arquivo;
    private javax.swing.JTextField campo_codigo;
    private javax.swing.JTextField campo_codigo_algoritmo;
    private javax.swing.JTextField campo_descricao_computador;
    private javax.swing.JTextField campo_descricao_solucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_area_pesquisa;
    // End of variables declaration//GEN-END:variables
}
